### PR TITLE
build: bump ops to latest possible version

### PR DESCRIPTION
**Pull request by DnPlas**
Part of canonical/bundle-kubeflow#868

### CODE REVIEW

**Comment by orfeas-k** [comment]
I see tests are failing due to mysql-k8s requirement of specific juju version https://github.com/canonical/mlflow-operator/actions/runs/9572177418/job/26390939593?pr=242#step:5:843. This is though because we use 8.0/edge while we should be using `stable` as we had agreed recently. Should we update its dependecy first?

**Comment by DnPlas** [comment]
> I see tests are failing due to mysql-k8s requirement of specific juju version https://github.com/canonical/mlflow-operator/actions/runs/9572177418/job/26390939593?pr=242#step:5:843. This is though because we use 8.0/edge while we should be using `stable` as we had agreed recently. Should we update its dependecy first?

I have left a comment https://github.com/canonical/mlflow-operator/pull/241#issuecomment-2176986345. Let's discuss over there.

**Comment by DnPlas** [comment]
Re-running CI because of

```
minio/0 [idle] error: unknown container reason "ImagePullBackOff": Back-off pulling image "registry.jujucharms.com/charm/81j63o4a2ldarn1umc22iyjz1q9l9g0sx5b8j/oci-image@sha256:1755999849a392bdf00b778705f4cf5c1c971a1ef55a17e9075e56f8d58bdc2f"
  mysql-k8s/0 [idle] error: unknown container reason "ImagePullBackOff": Back-off pulling image "registry.jujucharms.com/charm/62ptdfbrjpw3n9tcnswjpart30jauc6wc5wbi/mysql-image@sha256:8079d0631c91ca53d1d06b76afff4586811c1142e6c013fd6dc6d6d0a881c4a5"
```

**Review by orfeas-k — APPROVED** [review]
Regarding mysql, I replied to the other PR pointing in track.

**Pull request merged**
