### PR TITLE
ci: bump juju 3.1 -> 3.5 in track/2.1

### PR DESCRIPTION
**Pull request by DnPlas**
Part of canonical/bundle-kubeflow#859

### CODE REVIEW

**Comment by DnPlas** [comment]
The problem with the CI is that mysql-k8s 8.0/edge requires juju <3.5.0 or ==3.5.2, which hasn't been released. This CI will be blocked until we do either of:

a) Use mysql-k8s 8.0/stable - this is problematic because they will soon promote from 8.0/edge, which will leave us with the same issue
b) Pin juju to a different version, it can be 3.4.3

**Comment by orfeas-k** [comment]
I 'd go with a) since I 'd expect taking this requirement into account before promoting edge -> stable, since it's a breaking change in a way.

**Comment by DnPlas** [comment]
https://github.com/canonical/mlflow-operator/pull/246 should help fix the CI. Lets merge that before this one.

**Comment by DnPlas** [comment]
Closing this PR as it will be replaced by #241

**Pull request closed without merging**
