### PR TITLE
docs: tweaks to navigation headings

### PR DESCRIPTION
**Pull request by afgambin**
Some tweaks to update the navigation headings to follow the Diátaxis principles.

### CODE REVIEW

**Comment by afgambin** [comment]
@noha if you could have a look to this one :)

**Comment by noha** [comment]
@afgambin I think have a typo in the mention. I've never heard about this repo before ;)

**Comment by afgambin** [comment]
@NohaIhab if you could have a look to this one :)

**Review by NohaIhab — COMMENTED** [review]
small comment: this grid looks a bit odd now
I expected it to be left aligned
image

**Review by NohaIhab — APPROVED** [review]

**Pull request merged**
