### PR TITLE
fix: added unified s3 endpoint url generation

### PR DESCRIPTION
**Pull request by i-chvets**
https://github.com/canonical/mlflow-operator/issues/78

Summary of changes:
- Added unified S3 endpoint URL generation.

### CODE REVIEW

**Review by ca-scribner — APPROVED** [review]
lgtm provided the CI passes

**Comment by ca-scribner** [comment]
We also need to use namespace (but not port) on [this line](https://github.com/canonical/mlflow-operator/blob/0a3733c7934042563e3c45d27ece4ebe6c6e7109/charms/mlflow-server/src/charm.py#L301) to completely fix #77

**Comment by i-chvets** [comment]
> We also need to use namespace (but not port) on [this line](https://github.com/canonical/mlflow-operator/blob/0a3733c7934042563e3c45d27ece4ebe6c6e7109/charms/mlflow-server/src/charm.py#L301) to completely fix #77

This one will be fixed with this branch https://github.com/canonical/mlflow-operator/tree/kf-842-gh77-fix-service-with-namespace

**Comment by i-chvets** [comment]
@ca-scribner There was mistake in description. This PR is intended to fix #78

**Comment by ca-scribner** [comment]
ahh makes sense, if #77 is fixed elsewhere then lgtm

**Review by ca-scribner — APPROVED** [review]

**Pull request merged**
